credentials:
  usernames:
    davidl:
      email: david@gmail.com
      logged_in: False # Will be managed automatically
      name: David Lois
      password: walauwei # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: keybro # Must be string
  name: cookie
preauthorized:
  emails:
    - melsby@gmail.com
